services:
  - type: web
    name: shrtn-web
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/start.sh"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: shrtn-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: shrtn-redis
          type: redis
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: APP_HOST
        sync: false
      - key: SIDEKIQ_WEB_USERNAME
        sync: false
      - key: SIDEKIQ_WEB_PASSWORD
        sync: false
      - key: MAXMIND_LICENSE_KEY
        sync: false

  - type: redis
    name: shrtn-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

databases:
  - name: shrtn-db
    plan: free
    databaseName: shrtn
    user: shrtn
